#!/bin/bash

while read file
do
	case "$1" in
	"w")
		chwal $file
	;;
	"d")
		rm -rf $file
	;;
    "u")
		 waifu2x-ncnn-vulkan -i $file -o /home/john/Pictures/$(date +"%FT%H%M")-upscaled.png -n 3 -s 4
		 notify-send -t 4000 "Upscales completed!"
	 ;;
	 "t")
		  dragon-drop $file
    ;;

	esac
done

