#!/bin/sh

OUTDATED=$(pip --disable-pip-version-check list --outdated --format=json | python -c "import json, sys; print('\n'.join([x['name'] for x in json.load(sys.stdin)]))")

if [[ -z $OUTDATED ]]; then
	 echo "NO UPDATES"
	 exit 1
else
	 pip install -U $OUTDATED
fi
